<a href="https://colab.research.google.com/github/Mohit-Duggal/Python/blob/main/python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import numpy as np
import sys

numpy Basics

In [2]:
a = np.array([1,2,3,4],dtype='int16')
print(a)

[1 2 3 4]


In [3]:
b = np.array([[2.10,3.0,4.0],[5.0,6.0,7.0]])
print(b)

[[2.1 3.  4. ]
 [5.  6.  7. ]]


In [4]:
# get dimension
a.ndim

1

In [5]:
b.ndim

2

In [6]:
# get shape
b.shape

(2, 3)

In [7]:
# get type
a.dtype

dtype('int16')

In [8]:
# get size
a.itemsize

2

In [9]:
# get total size
a.nbytes

8

Accessing/Changing specifc element, rows, columns, etc

In [10]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [11]:
# get a specific element [r,c]
a[1,3]

10

In [12]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6])

In [13]:
# get a specific column
a[:,4]

array([ 5, 11])

In [14]:
# getting a little more speciific [startindex:endindex:stepsize]
a[0, 0:-1:2]

array([1, 3, 5])

In [15]:
a[1,2] = 15
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8, 15, 10, 11, 12]])

In [16]:
a[:,1] = [12,14]
a

array([[ 1, 12,  3,  4,  5,  6],
       [ 7, 14, 15, 10, 11, 12]])

3D array example

In [17]:
d = np.array([[[1,2,3],[3,4,4]],[[5,6,5],[7,8,8]]])
print(d)

[[[1 2 3]
  [3 4 4]]

 [[5 6 5]
  [7 8 8]]]


In [18]:
# get specific element
d[:,1,:]

array([[3, 4, 4],
       [7, 8, 8]])

In [19]:
d.shape

(2, 2, 3)

In [20]:
# replace
d[:,1,:] = [[1,1,1],[1,1,1]]
d

array([[[1, 2, 3],
        [1, 1, 1]],

       [[5, 6, 5],
        [1, 1, 1]]])

Initializing Differnet Types of Arrays

In [21]:
# all 0s matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [22]:
# all 1s matrix
np.ones((4,2,2), dtype='int8')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

In [23]:
# any other number
np.full((2,2),9,dtype='float32')

array([[9., 9.],
       [9., 9.]], dtype=float32)

In [24]:
# any other number (full_like)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [25]:
np.full_like(a,4)


array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [26]:
# random decimal number
np.random.rand(4,2,3)

array([[[0.43280646, 0.04793003, 0.17660472],
        [0.74731168, 0.096983  , 0.59111813]],

       [[0.18524229, 0.81756594, 0.17767666],
        [0.9562664 , 0.29985214, 0.89332372]],

       [[0.39151747, 0.65486278, 0.17653787],
        [0.74596092, 0.42674325, 0.58421665]],

       [[0.28706954, 0.92670886, 0.37035861],
        [0.05850586, 0.33017105, 0.7273061 ]]])

In [27]:
np.random.random_sample(a.shape)

array([[0.88978451, 0.57988973, 0.19844348, 0.13786582, 0.52455369,
        0.85124793],
       [0.1408214 , 0.40853217, 0.08385404, 0.79325181, 0.55380212,
        0.26789287]])

In [28]:
# random integer values
np.random.randint(-3,5,size=(3,5))

array([[ 4, -2,  2, -2,  0],
       [ 1,  3, -1,  1,  4],
       [-2,  1, -1, -1,  4]])

In [29]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
# repeat an array
arr = np.array([[1,2,3]])
r = np.repeat(arr,3, axis=0) 
r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [31]:
array = np.ones((5,5))
array


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
array1 = np.zeros((3,3))
array1[1,1] = 9
array1

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [33]:
array[1:4,1:4] = array1
array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

BE CAREFUL WHEN COPYING ARRAYS!

In [35]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [36]:
c = a.copy()
c[0] = 99
print(a,c)

[100   2   3] [99  2  3]


MATHEMATICS

In [37]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [38]:
a + 2

array([3, 4, 5, 6, 7])

In [39]:
a - 2

array([-1,  0,  1,  2,  3])

In [40]:
a * 2

array([ 2,  4,  6,  8, 10])

In [41]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [43]:
b = np.array([1,0,1,0,1])
a + b

array([2, 2, 4, 4, 6])

In [45]:
a**3

array([  1,   8,  27,  64, 125])

# TAKE THE SIN OR  COS 

In [46]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [47]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

LINEAR ALGEBRA

In [52]:
a = np.full((2,3),3)
print(a)

b = np.ones((3,2))
print(b)

[[3 3 3]
 [3 3 3]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [53]:
np.matmul(a,b)

array([[9., 9.],
       [9., 9.]])

In [58]:
c = np.identity(3)
print(c)
print(" ")
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 


1.0

STATISTICS

In [59]:
stat = np.array([[1,2,3],[6,5,4]])
stat

array([[1, 2, 3],
       [6, 5, 4]])

In [62]:
np.min(stat, axis=1)

array([1, 4])

In [63]:
np.max(stat, axis=1)

array([3, 6])

In [64]:
np.sum(stat)

21

REORGANIZING ARRAY

In [67]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((1,8))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [68]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [71]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1,h2)

np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] [[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

MISCELLANEOUS

In [79]:
#load data from file

filedata = np.genfromtxt('https://raw.githubusercontent.com/Mohit-Duggal/FMML-2022-Aug/main/num1.txt', delimiter=',')
print(filedata)

[[1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 2. 3. 4. 5. 6. 7. 8.]]


In [81]:
filedata= filedata.astype('int32')
print(filedata)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [83]:
# boolean masking and advanced indexing

filedata > 5

array([[False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True]])

In [84]:
filedata[filedata > 5]

array([6, 7, 8, 6, 7, 8, 6, 7, 8], dtype=int32)

In [85]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [88]:
np.all(filedata > 5,axis=1)

array([False, False, False])

In [96]:
((filedata > 2) & (filedata < 6))

array([[False, False,  True,  True,  True, False, False, False],
       [False, False,  True,  True,  True, False, False, False],
       [False, False,  True,  True,  True, False, False, False]])

In [95]:
(~((filedata > 2) & (filedata < 6)))

array([[ True,  True, False, False, False,  True,  True,  True],
       [ True,  True, False, False, False,  True,  True,  True],
       [ True,  True, False, False, False,  True,  True,  True]])